
import {
    GiHoodedFigure,
    GiGoblinHead,
    GiSkeleton,
    GiLute,
    GiFlute,
    GiLyre,
    GiBroadsword,
    GiBattleAxe,
    GiDagger,
    GiWizardStaff,
    GiFairyWand,
    GiMeat,
    GiCheeseWedge,
    GiGrapes,
    GiChickenLeg,
    GiRoundShield,
    GiBreastplate,
    GiVisoredHelm,
    GiGauntlet,
    GiCoins,
    GiJewelCrown,
    GiFlame,
    GiWaterDrop,
    GiLightningTrio,
    GiOakLeaf,
    GiBearTrap,
    GiScrollUnfurled,
} from 'react-icons/gi';

console.log("All imports successful");
